/**
 * HtmlReporter
 * Generates a styled HTML report with charts and comparisons.
 */

const fs = require('fs');
const path = require('path');

class HtmlReporter {
  constructor() {
    this.outputDir = path.join(__dirname, '../../results');
    this._ensureDir();
  }

  _ensureDir() {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  /**
   * Generate HTML report from optimization results.
   * @param {object} result - Optimization result.
   * @returns {string} Full HTML document.
   */
  format(result) {
    const { baseline, optimized, improvement, bottlenecks, recommendations } = result;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MiMo Optimizer Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0f; color: #e0e0e0; padding: 2rem; }
    .header { text-align: center; margin-bottom: 3rem; }
    .header h1 { font-size: 2rem; background: linear-gradient(135deg, #10b981, #06b6d4); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    .improvement { font-size: 1.5rem; color: #10b981; text-align: center; margin: 1rem 0; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; max-width: 900px; margin: 0 auto; }
    .card { background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 1.5rem; }
    .card h3 { color: #10b981; margin-bottom: 1rem; }
    .metric { display: flex; justify-content: space-between; padding: 0.5rem 0; border-bottom: 1px solid rgba(255,255,255,0.05); }
    .bottleneck { background: rgba(239,68,68,0.1); border-left: 3px solid #ef4444; padding: 0.75rem 1rem; margin: 0.5rem 0; border-radius: 0 8px 8px 0; }
    .recommendation { background: rgba(16,185,129,0.1); border-left: 3px solid #10b981; padding: 0.75rem 1rem; margin: 0.5rem 0; border-radius: 0 8px 8px 0; }
    .footer { text-align: center; margin-top: 3rem; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <h1>MiMo Agent Optimizer Report</h1>
    <p style="color:#888">${new Date().toISOString()}</p>
  </div>
  <div class="improvement">Improvement: ${improvement}</div>
  <div class="grid">
    <div class="card">
      <h3>Baseline</h3>
      <div class="metric"><span>Tokens</span><span>${baseline.metrics.totalTokens.toLocaleString()}</span></div>
      <div class="metric"><span>Latency</span><span>${baseline.metrics.latencyMs}ms</span></div>
      <div class="metric"><span>Cost</span><span>$${baseline.metrics.costUsd.toFixed(4)}</span></div>
    </div>
    <div class="card">
      <h3>Optimized</h3>
      <div class="metric"><span>Tokens</span><span>${optimized.metrics.totalTokens.toLocaleString()}</span></div>
      <div class="metric"><span>Latency</span><span>${optimized.metrics.avgLatency}ms</span></div>
      <div class="metric"><span>Cost</span><span>$${optimized.metrics.totalCost.toFixed(4)}</span></div>
    </div>
  </div>
  <div style="max-width:900px;margin:2rem auto">
    <h2 style="color:#10b981;margin-bottom:1rem">Bottlenecks</h2>
    ${bottlenecks.map((b) => `<div class="bottleneck"><strong>${b.severity.toUpperCase()}</strong> ${b.message}</div>`).join('\n    ')}
    <h2 style="color:#10b981;margin:2rem 0 1rem">Recommendations</h2>
    ${recommendations.map((r) => `<div class="recommendation"><strong>${r.action}</strong>: ${r.description}</div>`).join('\n    ')}
  </div>
  <div class="footer">Generated by MiMo Agent Auto-Optimizer v1.0.0</div>
</body>
</html>`;
  }

  /**
   * Write report to HTML file.
   * @param {object} result - Optimization result.
   * @returns {string} Path to the written file.
   */
  write(result) {
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const filePath = path.join(this.outputDir, `report-${ts}.html`);
    fs.writeFileSync(filePath, this.format(result), 'utf-8');
    return filePath;
  }
}

module.exports = HtmlReporter;
